### ISSUE TITLE
PHP 8.1 - Getting error method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given

### ISSUE THREAD

**Issue by leexin** [zhouaini528/huobi-php#15]
method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given
#0 /var/www/vendor/linwj/huobi/src/Request.php(167): method_exists()
#1 /var/www/vendor/linwj/huobi/src/Api/Spot/Order.php(21): Lin\Huobi\Request->exec()

When submitting order to Huobi calling $client->order()->postPlace()
Using PHP8.1

Probable fix to linwj/huobi/src/Request.php and linwj/binance/src/Request.php (might affect other exchanges Request.php too)
`if(method_exists($e->getResponse(),'getBody')){`
to be changed to 
`if( !empty($e->getResponse()) && method_exists($e->getResponse(),'getBody')){`

**Comment by zhouaini528** [comment]
Sorry I didn't find such a problem in PHP 8.1
![2023-01-04 09-30-23屏幕截图](https://user-images.githubusercontent.com/5442664/210468060-a0a7611b-4e47-4735-8d03-1b9dd0b9e71d.png)

**Comment by leexin** [comment]
@zhouaini528 same issue as mentioned in OKEX here https://github.com/zhouaini528/okex-php/issues/5

**Comment by zhouaini528** [comment]
> @zhouaini528 same issue as mentioned in OKEX here [zhouaini528/okex-php#5](https://github.com/zhouaini528/okex-php/issues/5)


Thanks for the discovery, I have solved the problem.
